### ISSUE TITLE
URLEncoder fails to encode exotic urls

### ISSUE THREAD

**Issue by laxika** [bottomless-archive-project/library-of-alexandria#15]
```
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 7: http://промкаталог.рф/PublicDocuments/05-0211-00.pdf
	at java.base/java.net.URI$Parser.fail(URI.java:2915) ~[na:na]
	at java.base/java.net.URI$Parser.parseHostname(URI.java:3450) ~[na:na]
	at java.base/java.net.URI$Parser.parseServer(URI.java:3299) ~[na:na]
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3218) ~[na:na]
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3160) ~[na:na]
	at java.base/java.net.URI$Parser.parse(URI.java:3116) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:685) ~[na:na]
	at com.github.loa.url.service.UrlEncoder.encode(UrlEncoder.java:28) ~[main/:na]
```

**Comment by laxika** [comment]
The URL is clearly invalid but it shouldn't kill the downloader application.

**Comment by laxika** [comment]
Fixed.

The URLEncoder returns an `Optional<URL>` in the future instead of an `URL`.
