### ISSUE TITLE
Sometimes the Vault Application fails

### ISSUE THREAD

**Issue by laxika** [bottomless-archive-project/library-of-alexandria#346]
See this exception:

```
2021-11-20 00:27:32.337  INFO 20184 --- [oundedElastic-1] c.g.l.v.service.VaultDocumentManager     : Archiving document with id: 6ae3ed96-ecaa-43e2-84a5-5b8371e93765.
2021-11-20 00:27:33.014 ERROR 20184 --- [oundedElastic-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: AMQ219060: Large Message Transmission interrupted on consumer shutdown.
Caused by: java.lang.RuntimeException: AMQ219060: Large Message Transmission interrupted on consumer shutdown.
        at org.apache.activemq.artemis.core.client.impl.ClientLargeMessageImpl.getBodyBuffer(ClientLargeMessageImpl.java:93) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at com.github.loa.queue.artemis.service.consumer.deserializer.DocumentArchivingMessageDeserializer.deserialize(DocumentArchivingMessageDeserializer.java:17) ~[loa-queue-artemis-service-1.4.0.jar!/:na]
        at com.github.loa.queue.artemis.service.consumer.deserializer.DocumentArchivingMessageDeserializer.deserialize(DocumentArchivingMessageDeserializer.java:11) ~[loa-queue-artemis-service-1.4.0.jar!/:na]
        at com.github.loa.queue.artemis.service.ArtemisQueueManipulator.lambda$readMessage$3(ArtemisQueueManipulator.java:147) ~[loa-queue-artemis-service-1.4.0.jar!/:na]
        at com.github.loa.queue.artemis.service.consumer.ClientConsumerExecutor.invokeConsumer(ClientConsumerExecutor.java:26) ~[loa-queue-artemis-service-1.4.0.jar!/:na]
        at com.github.loa.queue.artemis.service.ArtemisQueueManipulator.readMessage(ArtemisQueueManipulator.java:139) ~[loa-queue-artemis-service-1.4.0.jar!/:na]
        at com.github.loa.vault.service.listener.VaultQueueConsumer.accept(VaultQueueConsumer.java:22) ~[classes!/:1.4.0]
        at com.github.loa.vault.service.listener.VaultQueueConsumer.accept(VaultQueueConsumer.java:13) ~[classes!/:1.4.0]
        at reactor.core.publisher.FluxGenerate.lambda$new$1(FluxGenerate.java:57) ~[reactor-core-3.4.10.jar!/:3.4.10]
        at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:265) ~[reactor-core-3.4.10.jar!/:3.4.10]
        at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:207) ~[reactor-core-3.4.10.jar!/:3.4.10]
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:447) ~[reactor-core-3.4.10.jar!/:3.4.10]
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527) ~[reactor-core-3.4.10.jar!/:3.4.10]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.4.10.jar!/:3.4.10]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.4.10.jar!/:3.4.10]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.apache.activemq.artemis.api.core.ActiveMQLargeMessageInterruptedException: AMQ219060: Large Message Transmission interrupted on consumer shutdown.
        at org.apache.activemq.artemis.core.client.impl.LargeMessageControllerImpl.checkException(LargeMessageControllerImpl.java:334) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.LargeMessageControllerImpl.waitCompletion(LargeMessageControllerImpl.java:315) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.LargeMessageControllerImpl.saveBuffer(LargeMessageControllerImpl.java:275) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientLargeMessageImpl.checkBuffer(ClientLargeMessageImpl.java:159) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientLargeMessageImpl.getBodyBuffer(ClientLargeMessageImpl.java:91) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        ... 19 common frames omitted
Caused by: org.apache.activemq.artemis.api.core.ActiveMQLargeMessageInterruptedException: AMQ219060: Large Message Transmission interrupted on consumer shutdown.
        at org.apache.activemq.artemis.core.client.impl.LargeMessageControllerImpl.cancel(LargeMessageControllerImpl.java:207) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.resetLargeMessageController(ClientConsumerImpl.java:755) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.clearAtFailover(ClientConsumerImpl.java:528) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.handleFailover(ClientSessionImpl.java:1412) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.reconnectSessions(ClientSessionFactoryImpl.java:840) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.failoverOrReconnect(ClientSessionFactoryImpl.java:664) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.handleConnectionFailure(ClientSessionFactoryImpl.java:542) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.handleConnectionFailure(ClientSessionFactoryImpl.java:535) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.access$100(ClientSessionFactoryImpl.java:75) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl$1.run(ClientSessionFactoryImpl.java:398) ~[artemis-core-client-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:42) ~[artemis-commons-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:31) ~[artemis-commons-2.18.0.jar!/:2.18.0]
        at org.apache.activemq.artemis.utils.actors.ProcessorBase.executePendingTasks(ProcessorBase.java:65) ~[artemis-commons-2.18.0.jar!/:2.18.0]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118) ~[artemis-commons-2.18.0.jar!/:2.18.0]
```

**Comment by laxika** [comment]
Filed a bugreport to the Artemis devs: https://issues.apache.org/jira/browse/ARTEMIS-3588

**Comment by laxika** [comment]
The bugreport got closed by the Artemis devs without a proper resolution. Unfortunately, should be fixed entirely by us.
