### ISSUE TITLE
Elasticsearch highlighting exception

### ISSUE THREAD

**Issue by laxika** [bottomless-archive-project/library-of-alexandria#60]
```
org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=The length of [attachment.content] field of [6ed73fbbf06fa289abda1d954857fd2cd6dbe31882ccb791fb34ac265c01003d] doc of [vault_documents] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:491) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:432) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402) ~[elasticsearch-7.0.1.jar:7.0.1]
```

**Comment by laxika** [comment]
https://discuss.elastic.co/t/the-length-of-text-to-be-analyzed-for-highlighting-18031-exceeded-the-allowed-maximum-of-10000-set-for-the-next-major-elastic-version-for-large-texts-indexing-with-offsets-or-term-vectors-is-recommended/128740/6
